### PR TITLE
Updating to Guzzle 2.0

### PR DESCRIPTION
**Pull request by mtdowling**
Guzzle 2.0 was released the other day.  There's no longer caching built into the service builder (though it's now serializable if you need to cache it).  I haven't tested this, but I wanted to give you a good starting point for updating the bundle.

Thanks!

### CODE REVIEW

**Comment by HelloGrayson** [comment]
no go here?

**Comment by gimler** [comment]
+1

**Comment by gimler** [comment]
@ddeboer why you don't merge this one?

**Comment by gimler** [comment]
merged see https://github.com/ddeboer/GuzzleBundle/commit/1325e84cddeacd446e5438768ca264e4cea711a9#commitcomment-1562959

**Pull request closed without merging**
